### ISSUE TITLE
ServiceStack initializer complains about too many positional args

### ISSUE THREAD

**Issue by EandrewJones** [ran-isenberg/aws-lambda-handler-cookbook#585]
**Describe the bug**
Deploy fails. The code looks fine to me though.

**To Reproduce**
Follow steps from https://ran-isenberg.github.io/aws-lambda-handler-cookbook/getting_started/ exactly. `make deploy` fails.

**Expected behavior**
`make deploy` works.

**Screenshots**
![image](https://user-images.githubusercontent.com/41238273/229255696-6f8876fe-4bf0-4ee9-8a05-eb0561cd1247.png)

```python

class ServiceStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # This construct should be deployed in a different repo and have its own pipeline so updates can be decoupled
        # from running the service pipeline and without redeploying the service lambdas. For the sake of this template
        # example, it is deployed as part of the service stack
        self.dynamic_configuration = ConfigurationStore(
            self,
            f"{id}dynamic_conf"[0:64],
            ENVIRONMENT,
            SERVICE_NAME,
            CONFIGURATION_NAME,
        )
        self.lambdas = ApiConstruct(
            self, f"{id}Service"[0:64], self.dynamic_configuration.config_app.name
        )

```
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by EandrewJones** [comment]
Sorry for the ping.

**Comment by ran-isenberg** [comment]
Hey @EandrewJones , is this still an issue for you?
I can't seem to reproduce it. what was the problem?
