### ISSUE TITLE
feat: `cdk.json` could use `poetry run`

### ISSUE THREAD

**Issue by fiserv-plat-eng** [ran-isenberg/aws-lambda-handler-cookbook#619]
**Is your feature request related to a problem? Please describe.**

Currently `cdk.json` requires the cdk dependencies to be installed or run within `poetry shell`

**Describe the solution you'd like**

Changing the `cdk.json` to the following will allow `cdk` to run without extra streps.

```json
{
  "app": "poetry run python app.py"
}
```

__NOTE:__ `pip install` will no longer be needed in the github workflow

https://github.com/ran-isenberg/aws-lambda-handler-cookbook/blob/936588d277a05bba630fc44c46cda050eeec621c/.github/workflows/serverless-service.yml#L35

**Describe alternatives you've considered**

**Additional context**

**Comment by ran-isenberg** [comment]
resolved in #621 
Thx for opening the issue.
