### ISSUE TITLE
feat: use `npx cdk` to 

### ISSUE THREAD

**Issue by fiserv-plat-eng** [ran-isenberg/aws-lambda-handler-cookbook#620]
**Is your feature request related to a problem? Please describe.**

Makefile is expecting `cdk` to be installed and have a compatible version with the project

**Describe the solution you'd like**

Use a `package.json` to specify the version of cdk needed and a `script` to run is

```json
{
  "devDependencies": {
    "aws-cdk": "^2.78.0"
  },
  "scripts": {
    "cdk": "cdk"
  }
}
```

To keep the Makefile the same an alias for cdk can be made `alias cdk="npx aws-cdk"`

**Describe alternatives you've considered**

Documenting that an alias like this could also be used `alias cdk="npx aws-cdk"`

**Additional context**

- [CDK tips, part 1 – how to use local CDK commands](https://www.endoflineblog.com/cdk-tips-01-how-to-use-local-cdk-commands)
- [Using local tsc and cdk](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-typescript.html#typescript-local)

**Comment by ran-isenberg** [comment]
@fiserv-plat-eng  thx for the tip and feature suggestion.
I'll see when I can try and add it. I want to make sure i understand it.

**Comment by ran-isenberg** [comment]
@fiserv-plat-eng I think this one will be kept in the backlog as i will require to also update the windows makefile and i dont have a windows machine anymore. This is a nice feature to have, but not mandatory.
