### ISSUE TITLE
Feature request: GitLab version

### ISSUE THREAD

**Issue by codekiln** [ran-isenberg/aws-lambda-handler-cookbook#792]
**Is your feature request related to a problem? Please describe.**
As a gilab user, I'd like to use this cookbook. 

**Describe the solution you'd like**
Preferably, the cookiecutter interface would prompt me for whether I'm in gitlab or in github, and implement the appropriate files.

**Describe alternatives you've considered**
I'm considering implementing it for myself, but there are many items that are specific to github actions that aren't available in gitlab yet.

**Comment by ran-isenberg** [comment]
Hey @codekiln , thanks for showing interest in my project.
Since I don't use GitLab, i can't really verify and maintain any Gitlab code.
